[repositories]
rugix-extra = { git = "https://github.com/silitics/rugix-extra.git", branch = "v0.8" }

# Image based on Raspberry Pi OS using the `tryboot` feature for A/B booting.
#
# This image supports the Raspberry Pi 4 and 5 family of devices.
#
# Note that Raspberry Pi 4 devices need to have the latest firmware installed.
[systems.rpi-raspios]
layer = "rpi-raspios"
architecture = "arm64"
target = "rpi-tryboot"

# Like the `rpi-raspios` image but with the firmware update for Raspberry Pi 4.
[systems.rpi-raspios-pi4]
layer = "rpi-raspios-pi4"
architecture = "arm64"
target = "rpi-tryboot"

# Image based on Debian using the `tryboot` feature for A/B booting.
#
# This image supports the Raspberry Pi 4 and 5 family of devices.
#
# Note that Raspberry Pi 4 devices need to have the latest firmware installed.
[systems.rpi-debian]
layer = "rpi-debian"
architecture = "arm64"
target = "rpi-tryboot"

# Like the `rpi-debian` image but with the firmware update for Raspberry Pi 4.
[systems.rpi-debian-pi4]
layer = "rpi-debian-pi4"
architecture = "arm64"
target = "rpi-tryboot"

# Image based on Debian for EFI AMD64 systems.
[systems.efi-debian-amd64]
layer = "efi-debian"
architecture = "amd64"
target = "generic-grub-efi"

[systems.efi-debian-amd64-vm]
layer = "efi-debian"
architecture = "amd64"
target = "generic-grub-efi"
size = "16G"

# Image based on Debian for EFI ARM64 systems.
[systems.efi-debian-arm64]
layer = "efi-debian"
architecture = "arm64"
target = "generic-grub-efi"

[systems.efi-debian-arm64-vm]
layer = "efi-debian"
architecture = "arm64"
target = "generic-grub-efi"
size = "16G"

# Test system for Mender integration testing.
[systems.test-mender-efi-arm64]
layer = "test-mender-efi"
architecture = "arm64"
target = "generic-grub-efi"
